const db = require('./models')

const allHira = [
    {  ji: 'あ', romaji: 'a', bango: 1},
    {  ji: 'い', romaji: 'i', bango: 2},
    {  ji: 'う', romaji: 'u', bango: 3},
    {  ji: 'え', romaji: 'e', bango: 4},
    {  ji: 'お ', romaji: 'o', bango: 5},
    {  ji: 'か', romaji: 'ka', bango: 6},
    {  ji: 'き', romaji: 'ki', bango: 7},
    {  ji: 'く', romaji: 'ku', bango: 8},
    {  ji: 'け', romaji: 'ke', bango: 9},
    {  ji: 'こ', romaji: 'ko', bango: 10},
    {  ji: 'さ', romaji: 'sa', bango: 11},
    {  ji: 'し', romaji: 'shi', bango: 12},
    {  ji: 'す', romaji: 'su', bango: 13},
    {  ji: 'せ', romaji: 'se', bango: 14},
    {  ji: 'そ', romaji: 'so', bango: 15},
    {  ji: 'た', romaji: 'ta', bango: 16},
    {  ji: 'ち', romaji: 'chi', bango: 17},
    {  ji: 'つ', romaji: 'tsu', bango: 18},
    {  ji: 'て', romaji: 'te', bango: 19},
    {  ji: 'と', romaji: 'to', bango: 20},
    {  ji: 'な', romaji: 'na', bango: 21},
    {  ji: 'に', romaji: 'ni', bango: 22},
    {  ji: 'ぬ', romaji: 'nu', bango: 23},
    {  ji: 'ね', romaji: 'ne', bango: 24},
    {  ji: 'の', romaji: 'no', bango: 25},
    {  ji: 'は', romaji: 'ha', bango: 26},
    {  ji: 'ひ', romaji: 'hi', bango: 27},
    {  ji: 'ふ', romaji: 'fu', bango: 28},
    {  ji: 'へ', romaji: 'he', bango: 29},
    {  ji: 'ほ', romaji: 'ho', bango: 30},
    {  ji: 'ま', romaji: 'ma', bango: 31},
    {  ji: 'み', romaji: 'mi', bango: 32},
    {  ji: 'む', romaji: 'mu', bango: 33},
    {  ji: 'め', romaji: 'me', bango: 34},
    {  ji: 'も', romaji: 'mo', bango: 35},
    {  ji: 'や', romaji: 'ya', bango: 36},
    {  ji: 'ゆ', romaji: 'yu', bango: 37},
    {  ji: 'よ', romaji: 'yo', bango: 38},
    {  ji: 'ら', romaji: 'ra', bango: 39},
    {  ji: 'り', romaji: 'ri', bango: 40},
    {  ji: 'る', romaji: 'ru', bango: 41},
    {  ji: 'れ', romaji: 're', bango: 42},
    {  ji: 'ろ', romaji: 'ro', bango: 43},
    {  ji: 'わ', romaji: 'wa', bango: 44},
    {  ji: 'を', romaji: 'o', bango: 45},
    {  ji: 'ん', romaji: 'n', bango: 46},
    {  ji: 'が', romaji: 'ga', bango: 47},
    {  ji: 'ぎ', romaji: 'gi', bango: 48},
    {  ji: 'ぐ', romaji: 'gu', bango: 49},
    {  ji: 'げ', romaji: 'ge', bango: 50},
    {  ji: 'ご', romaji: 'go', bango: 51},
    {  ji: 'ざ', romaji: 'za', bango: 52},
    {  ji: 'じ', romaji: 'ji', bango: 53},
    {  ji: 'ず', romaji: 'zu', bango: 54},
    {  ji: 'ぜ', romaji: 'ze', bango: 55},
    {  ji: 'ぞ', romaji: 'zo', bango: 56},
    {  ji: 'だ', romaji: 'da', bango: 57},
    {  ji: 'ぢ', romaji: 'dji', bango: 58},
    {  ji: 'づ', romaji: 'dzu', bango: 59},
    {  ji: 'で', romaji: 'de', bango: 60},
    {  ji: 'ど', romaji: 'do', bango: 61},
    {  ji: 'ば', romaji: 'ba', bango: 62},
    {  ji: 'び', romaji: 'bi', bango: 63},
    {  ji: 'ぶ', romaji: 'bu', bango: 64},
    {  ji: 'べ', romaji: 'be', bango: 65},
    {  ji: 'ぼ', romaji: 'bo', bango: 66},
    {  ji: 'ぱ', romaji: 'pa', bango: 67},
    {  ji: 'ぴ', romaji: 'pi', bango: 68},
    {  ji: 'ぷ', romaji: 'pu', bango: 69},
    {  ji: 'ぺ', romaji: 'pe', bango: 70},
    {  ji: 'ぽ', romaji: 'po', bango: 71},
    {  ji: 'きゃ', romaji: 'kya', bango: 72},
    {  ji: 'きゅ', romaji: 'kyu', bango: 73},
    {  ji: 'きょ', romaji: 'kyo', bango: 74},
    {  ji: 'ぎゃ', romaji: 'gya', bango: 75},
    {  ji: 'ぎゅ', romaji: 'gyu', bango: 76},
    {  ji: 'ぎょ', romaji: 'gyo', bango: 77},
    {  ji: 'しゃ', romaji: 'sya', bango: 78},
    {  ji: 'しゅ', romaji: 'syu', bango: 79},
    {  ji: 'しょ', romaji: 'syo', bango: 80},
    {  ji: 'じゃ', romaji: 'jya', bango: 81},
    {  ji: 'じゅ', romaji: 'jyu', bango: 82},
    {  ji: 'じょ', romaji: 'jyo', bango: 83},
    {  ji: 'ちゃ', romaji: 'cya', bango: 84},
    {  ji: 'ちゅ', romaji: 'cyu', bango: 85},
    {  ji: 'ちょ', romaji: 'cyo', bango: 86},
    {  ji: 'にゃ', romaji: 'nya', bango: 87},
    {  ji: 'にゅ', romaji: 'nyu', bango: 88},
    {  ji: 'にょ', romaji: 'nyo', bango: 89},
    {  ji: 'ひゃ', romaji: 'hya', bango: 90},
    {  ji: 'ひゅ', romaji: 'hyu', bango: 91},
    {  ji: 'ひょ', romaji: 'hyo', bango: 92},
    {  ji: 'びゃ', romaji: 'bya', bango: 93},
    {  ji: 'びゅ', romaji: 'byu', bango: 94},
    {  ji: 'びょ', romaji: 'byo', bango: 95},
    {  ji: 'ぴゃ', romaji: 'pya', bango: 96},
    {  ji: 'ぴゅ', romaji: 'pyu', bango: 97},
    {  ji: 'ぴょ', romaji: 'pyo', bango: 98},
    {  ji: 'みゃ', romaji: 'mya', bango: 99},
    {  ji: 'みゅ', romaji: 'myu', bango: 100},
    {  ji: 'みょ', romaji: 'myo', bango: 101},
    {  ji: 'りゃ', romaji: 'rya', bango: 102},
    {  ji: 'りゅ', romaji: 'ryu', bango: 103},
    {  ji: 'りょ', romaji: 'ryo', bango: 104},
]

const hiraganaSeed = async() => {
    await db.Hira.insertMany(allHira)
    console.log(`Seeded database with ${allHira}`)
}

hiraganaSeed()